name: ESDP_digital_ocean

services:
  - name: server
    github:
      repo: romeeeoo/ESDP_digital_ocean
      branch: main
      deploy_on_push: true
    run_command: python manage.py runserver 0.0.0.0:8080
    http_port: 8000

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: romeeeoo/ESDP_digital_ocean
      branch: main
      deploy_on_push: true
    run_command: python manage.py migrate